let LEVELS =
[
    [
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                    o                 o                   ",
        "                                                                          ",
        "                                 xxxxxxx        x     x                   ",
        "                           o    x       x       x!!!!!x                   ",
        "                                x       x       x!!!!!x                   ",
        "                           x    x       x       x!!!!!x                   ",
        "                                x              xxxxxxxxxx                 ",
        "                                x               x     x                   ",
        "                       x        x               x     x                   ",
        "                                x               x     x                   ",
        "                                x               x     x                   ",
        "                           x    x               x     x  o                ",
        "                                x               x     x                   ",
        "                                x              xxxxxxxxxxx                ",
        "                       x        x!!!!!!!x       x     x                   ",
        "                                x!!!!!!!x       x     x                   ",
        "  xx                            x!!!!!!!x       x     x               xx  ",
        "  x                        x     xxxxxxx        x     x                x  ",
        "  x                      o                                             x  ",
        "  x                                                                    x  ",
        "  x                    xxxxx             x!!!!x                        x  ",
        "  x            o   o   x   x             x!!!!x                     o  x  ",
        "  x  @                 x   x             x!!!!x                        x  ",
        "  xxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  "
    ],
    [
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                                                                          ",
        "                    o   o       o          o       o                      ",
        "                                                                          ",
        "                    x   x x     x xxx   xxxx  xxx  x                      ",
        "                    x   x xx    x x  x  x    x   x x                      ",
        "                  x x   x x x   x x x   x    x   x x                      ",
        "                    x   x x  x  x xx    xxxx xxxxx x                      ",
        "              o x   x   x x   x x x x   x    x   x x   o                  ",
        "                    x!!!x x    xx x  x  x    x   x x                      ",
        "  xx          x      xxx  x     x x   x xxxx x   x xxxxx              xx  ",
        "  x                                                                    x  ",
        "  xx=      ox                    =                                    xx  ",
        "  x                                                                    x  ",
        "  x     x  x x  x x xxxxx x o x                                        x  ",
        "  x     x  x xx!x x   x    x x                                         x  ",
        "  x  @  x!!x x xx x   x     x   xxxx                                   x  ",
        "  xxxxx!!xx!!x  x!x!!!x!!!!!x!!x    x       =          xxxxxxxxxxxxxxxxx  ",
        "                               x        x      x      x                   ",
        "                               x        x  o   x  o                       ",
        "                               x        x      x    x                     ",
        "                               x o   xxxxxxxxxxxxxx                       ",
        "                               x    x   x      x                          ",
        "                                xxxx    x      x!!!!!!!!!!!!!!!!!!!!!!!!  "
    ],
    [
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                                                      ",
        "                                o                                     ",
        "                             x                                        ",
        "                          x  xxxxx                                    ",
        "                             xxxxxxxx                                 ",
        "                   o   x     xxxxxxxxxx                               ",
        "                             xxxxx xxxxx                              ",
        "                   x         xxxxx xxxxx   o                          ",
        "                             xxxxx xxxxxx                             ",
        "                      x|  |  xxxxx xxxxxx  x                          ",
        "                             xxxxx xxxxxx                             ",
        "  xx                     x o xxxxx xxxxxx                         xx  ",
        "  x                |         xxxxx xxxxx   | x                     x  ",
        "  x                         xxxxxx xxxx                            x  ",
        "  x                      xxxxxxxxx    xxxx                         x  ",
        "  x                   xxxxxxxxxxxxxxxxxxxxxxxx          =          x  ",
        "  x                xxxxxxxx  xxxxxxxxxx   xxxx            o        x  ",
        "  x  @             xxxxx    xxxxxxxx    xxxxxx                     x  ",
        "  xxxxxxxxxxxxxxx!xxxxx  xxxxxxxxx   xxxxxxxx xxxxxxxxxxxxxxxxxxxxxx  ",
        "                   xxxxxxxxxxxxxxxxxxxxxxxx                           ",
        "                             xxxxxxxxxxx                              ",
        "                              xxxxxxx                                 ",
        "                                 x                                    "
    ],
    [
        "                                                   ",
        "                                                   ",
        "                                                   ",
        "                 x       x       x                 ",
        "                xxx     xxx     xxx                ",
        "               xx xx   xx xx   xx xx               ",
        "               xx xx   xx xx   xx xx               ",
        "                xvx     xvx     xvx                ",
        "                                                   ",
        "                                                   ",
        "                                                   ",
        "                                                   ",
        "                                                   ",
        "  xx                                           xx  ",
        "  x                                             x  ",
        "  x             o                 o             x  ",
        "  x                                             x  ",
        "  x             xx               xx             x  ",
        "  x                                        o    x  ",
        "  x  @               !!!!x!!!!                  x  ",
        "  xxxxxxxxxxxxxx!!!!!!xxxxxxx!!!!!!xxxxxxxxxxxxxx  ",
        "                !!!!!xxxxxxxxx!!!!!                ",
        "                !!!!!!!xxxxx!!!!!!!                ",
        "                !!xxx!!!!x!!!!xxx!!                ",
        "                !xxxxx!!!!!!!xxxxx!                ",
        "               !!xxxxxxx!!!xxxxxxx!!               ",
        "               !xxxxxxx!!!!!xxxxxxx!               ",
        "               !xxxxxx!!!!!!!xxxxxx!               ",
        "               !xxxxx!!!!x!!!!xxxxx!               ",
        "               !xxxxx!!xxxxx!!xxxxx!               ",
        "               !xxxx!!xxxxxxx!!xxxx!               ",
        "               !xxxx!xxxxxxxxx!xxxx!               ",
        "               !xxx!!xxxxxxxxx!!xxx!               ",
        "               !!xx!xxxxxxxxxxx!xx!!               ",
        "                !x!!xxxxxxxxxxx!!x!                ",
        "                !!!xxxxxxxxxxxxx!!!                ",
        "                  !xxxxxxxxxxxxx!                  ",
        "                  !!xxxxxxxxxxx!!                  ",
        "                   !!!xxxxxxx!!!                   ",
        "                     !!!!!!!!!                     "
    ],
    [
        "                                                          ",
        "                                                          ",
        "                                                          ",
        "              x              x               x            ",
        "             xxx            xxx             xxx           ",
        "            xx xx          xx xx           xx xx          ",
        "            xx xx          xx xx           xx xx          ",
        "             xvx            xvx             xvx           ",
        "                                                          ",
        "                                                          ",
        "                                                          ",
        "                                                          ",
        "  xx                                                  xx  ",
        "  x                                                    x  ",
        "  x                                                    x  ",
        "  x                                                    x  ",
        "  x                                            o       x  ",
        "  x                                                    x  ",
        "  x  @                                                 x  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
        "      x                                            x      ",
        "     x                                     x        x     ",
        "    x    x    x x         x   xx           x         x    ",
        "    x   x x   x    x xx  xxx x  x x xx   xxx  xx     x    ",
        "    x   x  x  x x  xx  x  x x xx  xx  x x  x x  x    x    ",
        "    x   x   x x x  x   x  x x     x   x x  x x  x    x    ",
        "     x  x    x  x  x   x  x  xxxx x   x  xx   xx    x     ",
        "      x                                            x      ",
        "       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       "
    ]
];